export const emptyBusiness = {
  name: "",
  description: "",
  phone: "",
  whatsapp: "",
  email: "",
  website: "",
  address: "",
  logoUrl: "",
  facebook: "",
  instagram: "",
  linkedin: "",
  tiktok: "",
  youtube: "",
  xTwitter: "",
  telegram: "",
  snapchat: "",
  pinterest: "",
  openingHours: "",
  isPublished: false,
  accentColor: "#0d9488",
  siteMode: "qr",
  theme: "gradient",
  heroTitle: "",
  heroSubtitle: "",
  coverImage: "",
  galleryImages: [""],
  services: [{ title: "", description: "", icon: "" }],
  aboutTitle: "",
  aboutText: "",
  testimonials: [{ name: "", role: "", message: "", avatar: "" }],
  faqItems: [{ question: "", answer: "" }],
  ctaTitle: "",
  ctaText: ""
};
